### ISSUE TITLE
Mark posts as duplicates

### ISSUE THREAD

**Issue by choreff** [LithiumH/piazza-bot#2]
Instead of repeating answers, link duplicate posts to a single question so that answer improvements propagate to all students. Also, marking as duplicates reduces Piazza clutter.

**Comment by LithiumH** [comment]
#3 This issue is dupliacted

**Comment by jbaek080** [comment]
lol so meta

**Comment by jbaek080** [comment]
someone make a github bot to mark as duplicate duplicate issues
